spring:
  application:
    name: blogdulich
  mongodb:
    uri: "mongodb+srv://<username>:<password>@cluster0.mquwt9e.mongodb.net/sample_mflix?readPreference=primaryPreferred"


jwt:
  signerKey: "your-super-secret-key"

defaultImage:
  avartar: "https://res.cloudinary.com/desoarfu8/image/upload/v1759670502/samples/man-portrait.jpg"

cloudinary:
  cloud-name: "Username"
  api-key: "api-key"
  api-secret: "api secret"
